import { database } from '@/lib/storage';
import { roundById, rounds, type Person } from '@/lib/rounds';
export class AppError extends Error{constructor(message:string,public status=400){super(message)}}
export async function digest(s:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(b=>b.toString(16).padStart(2,'0')).join('');}
export const token=()=>crypto.randomUUID()+crypto.randomUUID();
export async function authenticate(req:Request){const raw=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!raw)throw new AppError('Abra seu link de entrada para continuar.',401);const hash=await digest(raw);const room=await database().prepare('SELECT * FROM rooms WHERE pedro = ? OR mariana = ?').bind(hash,hash).first<{id:string;pedro:string;mariana:string;playlist:string;position:number}>();if(!room)throw new AppError('Este link de entrada não é válido.',401);const person:Person=room.pedro===hash?'Pedro':'Mariana';const playlist:string[]=JSON.parse(room.playlist);return {room,person,playlist};}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','Referrer-Policy':'no-referrer'}})}
export function failure(e:unknown){if(e instanceof AppError)return json({error:e.message},e.status);console.error('session failure',e);return json({error:'Não foi possível salvar agora. Sua resposta continua aqui. Tente novamente.'},503);}
// Single visibility rule shared by the live session and the export: own answers, or answers of rounds already revealed.
export function visibleAnswers<T extends Record<string,unknown>>(all:T[],revs:Record<string,unknown>[],person:Person,now:number){return all.filter(a=>a.person===person||revs.some(r=>r.round===a.round&&Number(r.at)<=now));}
export async function snapshot(req:Request){const {room,person,playlist}=await authenticate(req);const db=database();const all=(await db.prepare('SELECT * FROM answers WHERE room = ?').bind(room.id).all()).results;const revs=(await db.prepare('SELECT * FROM reveals WHERE room = ?').bind(room.id).all()).results;const now=Date.now();const visible=visibleAnswers(all,revs,person,now);return {room:room.id,person,position:room.position,playlist,rounds:playlist.map(roundById),answers:visible,reveals:revs.map(r=>({...r,joint:Number(r.at)<=now?r.joint:null})),submitted:all.filter(a=>a.round===playlist[room.position]).map(a=>a.person),memories:all.length+revs.filter(r=>r.decision==="joint").length,serverTime:now,complete:room.position>=playlist.length};}
export async function current(req:Request,id:unknown){const auth=await authenticate(req);if(auth.playlist[auth.room.position]!==id)throw new AppError('A rodada mudou. Atualize para continuar.',409);return {...auth,round:roundById(id as string)};}

